clone_depth: 10

version: 1.0.{build}

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DDECAF_BUILD_TOOLS=ON ..
  - cd ..

build:
  project: build/decaf-emu.sln
  parallel: true
  verbosity: minimal

after_build:
  - cd build\obj\Release
  - 7z a decaf-bin.zip
      decaf-sdl.exe
      decaf-cli.exe
      gfd-tool.exe
      latte-assembler.exe
      pm4-replay.exe
      zlib1.dll
      glbinding.dll
      SDL2.dll
      resources\fonts\DejaVuSansMono.ttf
      resources\fonts\SourceSansPro-Regular.ttf
      resources\fonts\LICENSE.txt

artifacts:
  - path: build\obj\Release\decaf-bin.zip
    name: decaf-bin
